Blog app - Views
david-lafontant/my_blog_app pull request #5
Opened 2022-05-20 20:37 UTC by david-lafontant

Implement the design and requirements described in this [link](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=Project%20requirements,described%20here.)

2022-05-20 20:50 UTC, GzimAsani requested changes
### Hi @david-lafontant 
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Awesome job, I really liked your project :wave: 
 
 ## Required Changes 
- [ ]  I am having problems creating the Postgres database. Kindly check again the database.yml file. 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 23:12 UTC, david-lafontant commented
> ### Hi @david-lafontant
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * Awesome job, I really liked your project 👋
> 
> ## Required Changes
> * [ ]   I am having problems creating the Postgres database. Kindly check again the database.yml file.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding! clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you @GzimAsani ! For the database, you have to modify the database.yml by replacing the username `postgres` with your own username and the password `admin` with your own password. I'm on windows and my installation was made in plain windows without wsl. I annotated the `database.yml` file in order to facilitate this. Once you replace the password and the username in `database.yml` with your own you could type `rails db:reset` to run the database again (because it was already there) as you can see it it the picture below.

![response](https://user-images.githubusercontent.com/39683557/169623173-3cb0d90a-b212-4e95-90e0-ec487b9f827b.png)

2022-05-21 05:10 UTC, sheylaPozo commented
## Status: ✔️ Project Approved ✔️ 
----

Hello @david-lafontant 🔥 

> # Excellent work on your project, it looks very professional and it's completed. Congrats on the good work!

![surprised](https://user-images.githubusercontent.com/60631456/122959988-c881fc00-d348-11eb-988a-a5aa782f4777.gif)

Now you can celebrate! 🥇 🚀 👍 💯 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️
`There's nothing left to say but time to merge! 😊`

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-21 05:11 UTC, sheylaPozo approved these changes

2022-05-21 06:42 UTC, merged